#!/bin/sh

# launch at bspwm startup
sxhkd &


## handle second screen connection
external_screen = $(xrandr --query | grep 'HDMI-1-1')
sleep 1
if [[ $external_screen = HDMI-1-1\ connected* ]]; then
	xrandr --output eDP-1 --mode 1920x1080 --rotate normal
	xrandr --output HDMI-1-1 --primary --mode 2560x1440 --rate 143.91 --rotate normal --left-of eDP-1
	bspc monitor HDMI-1-0 -d 1 2 3 4
	bspc monitor eDP-1 -d 5 6 7 8 
else
	xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

feh --bg-fill ~/Images/Wallpapers/wallpapers.jpg
~/.config/polybar/launch-alter.sh 

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bpsc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config top_padding 1


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='5'
bspc rule -a discord desktop='4'
#bspc rule -a polybar sticky=on

# xsetroot -cursor-name left_ptr &
#xautolock -detectsleep -time 10 -locker "better #autolock screen
#/usr/lib/polkit-gnome/polkit-gnome-authentification-agent-1 &
/usr/lib/polkit-kde-authentification-agent-1 &
# ~/.config/bspwm/scripts/only-focused-window-border &

if [[ $(pgrep picom) ]]; then
	killall picom
fi
picom &

numlockx on &
dunst &
